# Generated by Django 3.0.8 on 2020-08-13 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connectForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('live service', 'LIVE SERVICE'), ('online', 'ONLINE')], default='live service', max_length=15)),
                ('salutation', models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.')], default='mr', max_length=5)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('phoneNumber', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('email', models.CharField(max_length=40)),
                ('addressLine1', models.CharField(max_length=50)),
                ('addressLine2', models.CharField(max_length=50)),
                ('addressCity', models.CharField(max_length=20)),
                ('addressState', models.CharField(max_length=20)),
                ('addressZip', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('addressCountry', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
