# Generated by Django 3.0.8 on 2020-08-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifgfoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectform',
            options={'verbose_name': 'Connect Card'},
        ),
    ]
