# Generated by Django 3.0.8 on 2020-08-13 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifgfoc', '0002_auto_20200812_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectform',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='connectform',
            name='phoneNumber',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
