# Generated by Django 3.0.8 on 2020-08-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifgfoc', '0003_auto_20200812_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectform',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='connectform',
            name='service',
        ),
    ]
