# Generated by Django 3.0.8 on 2020-08-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifgfoc', '0004_auto_20200813_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectform',
            name='salutation',
            field=models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.')], default='mr', max_length=5),
        ),
        migrations.AddField(
            model_name='connectform',
            name='service',
            field=models.CharField(choices=[('live service', 'LIVE SERVICE'), ('online', 'ONLINE')], default='live service', max_length=15),
        ),
    ]
