# Generated by Django 3.0.8 on 2020-08-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifgfoc', '0005_auto_20200813_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectform',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='connectform',
            name='service',
        ),
    ]
