# Generated by Django 3.0.8 on 2020-08-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifgfoc', '0006_auto_20200813_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectform',
            name='addressZip',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='connectform',
            name='phoneNumber',
            field=models.PositiveIntegerField(),
        ),
    ]
