# Generated by Django 3.0.8 on 2020-08-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifgfoc', '0008_prayerform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayerform',
            old_name='prayerRequest',
            new_name='prayerRequests',
        ),
    ]
